### ISSUE TITLE
Allow users to suggest new discipline when suggesting the scholar

### ISSUE THREAD

**Issue by bishesh** [AbhinavNepal/abhinav-nepal#10]
Someone trying to add a scholar sent a message:
"I tried to add myself to the scholar database but there is no section for HCI under CS category. And I didn't see ways to add 'other' as well. Possibly a design issue."

@biwek  This is an urgent issue because many people trying to add can be put off by not having their disciplines in the drop down. Can we have 'other' appearing in the drop down like: "Other (suggest new discipline)" and when they select this allow them to enter in a field "New Discipline that best fits the added scholar:" 
Something like this ?

**Comment by biwek** [comment]
There is a [task](https://github.com/AbhinavNepal/abhinav-nepal/projects/1#card-11989582) in the queue which looks at the ability to add disciplines as a moderator/admin.

As a quick approach however I've pushed https://github.com/AbhinavNepal/abhinav-nepal/commit/43ce5af7b0c69bce40a595901a28b4d42ffc3ab3, which basically, as suggested adds 'Other' option to the discipline field. This also triggers an input field for the user to input his/her discipline.
