### ISSUE TITLE
Provide option of adding contributor's name

### ISSUE THREAD

**Issue by bishesh** [AbhinavNepal/abhinav-nepal#7]
Currently when a non-admin adds scholars, we are asking email address, but not their names. Can we provide an optional field where they can add their names ? We can also have a message next to this field saying that "This is optional. If you provide it, it will be added to the list of contributors in the website". 
Then, we can have a page in the website where we make public all the contributors (of course who chose to provide their names.

**Comment by biwek** [comment]
I like the idea of showcasing scholar contributors but I feel having optional name fields becomes a bit of an annoyance for a returning contributor. 🤔 
Guess we could try and see what the feedback is.

**Comment by biwek** [comment]
Addressed in https://github.com/AbhinavNepal/abhinav-nepal/pull/8.
